### ISSUE TITLE
NRH is re-deleting old posts that should have been deleted the first time around

### ISSUE THREAD

**Issue by PsychoNavigator** [sr33/Nuke-Reddit-History#1]
I used this extension on chrome about a month ago and cleaned out about 7 years of content supposedly.

I ran it again today to clean out comments, and it's now going page after page with random comments in no discernable order, but you'll see that it's got several comments from different timeframes.

These should all have been deleted, and going to my profile page on reddit shows that there isn't anything there, yet this extension seems to be finding them all.

I am trying to figure out what's going on exactly. How is this extension able to pull up comments that reddit shows as having been deleted? Does this plug in cache my old comments for some reason?

![image](https://user-images.githubusercontent.com/3032289/38594223-a816807a-3d88-11e8-9cf5-0fc5414c53e2.png)

**Comment by sr33** [comment]
Hello,

Sorry about the delayed response. I can assure you that the extension does not have any capabilities built-in to save or cache your old comments for any reason. All it does is automate the process of overwriting and deletion.

Trying to figure out why your comments get resurfaced is a difficult question.
It is a well known fact that reddit shows the latest 1000 comments and nothing more. I'm just speculating here but maybe because you delete the latest 1000 comments, reddit is recaching the next set of 1000 comments and displaying them to you.

Alternatively, the extension's had some trouble with going through all sort orders and effectively deleting all of the [1000] comments that reddit shows to you. I should get back to fixing that bug.
